// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzAm6d_SOnvRx27ZwUGWkT2kVXgl9sIE',
    appId: '1:798204071430:web:6a74c716e4612f4b093d87',
    messagingSenderId: '798204071430',
    projectId: 'fb-miner-app',
    authDomain: 'fb-miner-app.firebaseapp.com',
    storageBucket: 'fb-miner-app.appspot.com',
    measurementId: 'G-BCJF7J273P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy3P8PKAIax_4xo5kRkq3j5BYrOa38VNg',
    appId: '1:798204071430:android:512507368b21c182093d87',
    messagingSenderId: '798204071430',
    projectId: 'fb-miner-app',
    storageBucket: 'fb-miner-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc45x7aIwb0B2q9KkAa0EfJ2_p9qd7sxM',
    appId: '1:798204071430:ios:16e4b2dc303ab144093d87',
    messagingSenderId: '798204071430',
    projectId: 'fb-miner-app',
    storageBucket: 'fb-miner-app.appspot.com',
    iosBundleId: 'com.example.firebaseMiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc45x7aIwb0B2q9KkAa0EfJ2_p9qd7sxM',
    appId: '1:798204071430:ios:16e4b2dc303ab144093d87',
    messagingSenderId: '798204071430',
    projectId: 'fb-miner-app',
    storageBucket: 'fb-miner-app.appspot.com',
    iosBundleId: 'com.example.firebaseMiner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJzAm6d_SOnvRx27ZwUGWkT2kVXgl9sIE',
    appId: '1:798204071430:web:0fe8ef81bb744a05093d87',
    messagingSenderId: '798204071430',
    projectId: 'fb-miner-app',
    authDomain: 'fb-miner-app.firebaseapp.com',
    storageBucket: 'fb-miner-app.appspot.com',
    measurementId: 'G-P7Z93W2QFB',
  );
}
